package paprika

// defaultAisleKeywords maps common ingredient keywords to canonical aisle names.
// Keywords are checked as whole-word matches against the normalized ingredient
// name. More-specific (longer) keywords are listed first so they take precedence.
//
// Aisle names are verified against the user's actual Paprika aisles at lookup
// time; if the user does not have a matching aisle the entry is skipped.
// To extend, add entries here; the canonical name should match what Paprika
// commonly uses (Produce, Dairy, Meat, etc.).
// aisleAliases maps canonical aisle names (as used in the keyword/modifier
// tables) to alternate names a user might give the same aisle in Paprika.
// resolveAisleName tries the canonical name first, then each alias.
// All comparisons are case-insensitive.
var aisleAliases = map[string][]string{
	"Canned Goods": {"Canned", "Canned & Jarred", "Cans", "Jarred Goods"},
	"Baking":       {"Baking Goods"},
	"Spices":       {"Spices & Seasonings", "Seasonings"},
	"Bakery":       {"Bread", "Bread & Bakery"},
	"Frozen":       {"Frozen Foods"},
	"Snacks":       {"Chips & Snacks"},
	"Dairy":        {"Dairy & Eggs"},
	"Meat":         {"Meat & Seafood"},
	"Produce":      {"Fruits & Vegetables"},
}

var defaultAisleKeywords = []struct{ keyword, aisle string }{
	// ── Multi-word (checked before single-word to avoid false matches) ──────

	// Frozen
	{"frozen pizza", "Frozen"},
	{"frozen meal", "Frozen"},
	{"frozen meals", "Frozen"},
	{"frozen dinner", "Frozen"},
	{"frozen dinners", "Frozen"},
	{"frozen vegetable", "Frozen"},
	{"frozen vegetables", "Frozen"},
	{"frozen fruit", "Frozen"},
	{"frozen burritos", "Frozen"},
	{"frozen peas", "Frozen"},
	{"fish sticks", "Frozen"},
	{"tater tots", "Frozen"},
	{"ice cream", "Frozen"},
	{"frozen yogurt", "Frozen"},
	{"pot pie", "Frozen"},
	{"edamame", "Frozen"},

	// Canned / Pantry
	{"chicken broth", "Canned Goods"},
	{"beef broth", "Canned Goods"},
	{"vegetable broth", "Canned Goods"},
	{"chicken stock", "Canned Goods"},
	{"beef stock", "Canned Goods"},
	{"coconut milk", "Canned Goods"},
	{"almond milk", "Canned Goods"},
	{"oat milk", "Canned Goods"},
	{"canned tomatoes", "Canned Goods"},
	{"tomato paste", "Canned Goods"},
	{"tomato sauce", "Canned Goods"},
	{"diced tomatoes", "Canned Goods"},
	{"crushed tomatoes", "Canned Goods"},
	{"whole tomatoes", "Canned Goods"},
	{"tomato puree", "Canned Goods"},
	{"black beans", "Canned Goods"},
	{"kidney beans", "Canned Goods"},
	{"chickpeas", "Canned Goods"},
	{"garbanzo beans", "Canned Goods"},
	{"pinto beans", "Canned Goods"},
	{"baked beans", "Canned Goods"},
	{"refried beans", "Canned Goods"},
	{"lentils", "Canned Goods"},
	{"corn niblets", "Canned Goods"},
	{"green beans", "Canned Goods"},
	{"canned tuna", "Canned Goods"},
	{"canned salmon", "Canned Goods"},
	{"canned sardines", "Canned Goods"},
	{"canned clams", "Canned Goods"},
	{"pumpkin puree", "Canned Goods"},
	{"apple sauce", "Canned Goods"},
	{"applesauce", "Canned Goods"},

	// Bakery
	{"corn tortillas", "Bakery"},
	{"flour tortillas", "Bakery"},
	{"sourdough bread", "Bakery"},
	{"whole wheat bread", "Bakery"},
	{"white bread", "Bakery"},
	{"hamburger buns", "Bakery"},
	{"hot dog buns", "Bakery"},
	{"dinner rolls", "Bakery"},
	{"croissants", "Bakery"},
	{"english muffins", "Bakery"},

	// Baking
	{"baking powder", "Baking"},
	{"baking soda", "Baking"},
	{"corn starch", "Baking"},
	{"cornstarch", "Baking"},
	{"cream of tartar", "Baking"},
	{"vanilla extract", "Baking"},
	{"almond extract", "Baking"},
	{"cocoa powder", "Baking"},
	{"chocolate chips", "Baking"},
	{"brown sugar", "Baking"},
	{"powdered sugar", "Baking"},
	{"confectioners sugar", "Baking"},
	{"bread flour", "Baking"},
	{"cake flour", "Baking"},
	{"all purpose flour", "Baking"},
	{"whole wheat flour", "Baking"},
	{"maple syrup", "Baking"},
	{"agave syrup", "Baking"},
	{"food coloring", "Baking"},

	// Beverages
	{"sparkling water", "Beverages"},
	{"orange juice", "Beverages"},
	{"apple juice", "Beverages"},
	{"cranberry juice", "Beverages"},
	{"grape juice", "Beverages"},
	{"tomato juice", "Beverages"},
	{"sports drink", "Beverages"},
	{"energy drink", "Beverages"},
	{"protein shake", "Beverages"},

	// Personal care / household
	{"dish soap", "Household"},
	{"laundry detergent", "Household"},
	{"paper towels", "Household"},
	{"toilet paper", "Household"},
	{"trash bags", "Household"},
	{"aluminum foil", "Household"},
	{"plastic wrap", "Household"},
	{"parchment paper", "Household"},
	{"zip lock bags", "Household"},
	{"ziploc bags", "Household"},
	{"hand soap", "Personal Care"},
	{"shampoo", "Personal Care"},
	{"conditioner", "Personal Care"},
	{"toothpaste", "Personal Care"},
	{"toothbrush", "Personal Care"},
	{"deodorant", "Personal Care"},
	{"body wash", "Personal Care"},

	// ── Single-word keywords ────────────────────────────────────────────────

	// Produce
	{"apple", "Produce"},
	{"apricot", "Produce"},
	{"asparagus", "Produce"},
	{"avocado", "Produce"},
	{"banana", "Produce"},
	{"basil", "Produce"},
	{"beet", "Produce"},
	{"bell pepper", "Produce"},
	{"blueberry", "Produce"},
	{"broccoli", "Produce"},
	{"brussels", "Produce"},
	{"cabbage", "Produce"},
	{"cantaloupe", "Produce"},
	{"carrot", "Produce"},
	{"cauliflower", "Produce"},
	{"celery", "Produce"},
	{"cherry", "Produce"},
	{"cilantro", "Produce"},
	{"corn", "Produce"},
	{"cucumber", "Produce"},
	{"dill", "Produce"},
	{"eggplant", "Produce"},
	{"fennel", "Produce"},
	{"garlic", "Produce"},
	{"ginger", "Produce"},
	{"grape", "Produce"},
	{"grapefruit", "Produce"},
	{"jalapeno", "Produce"},
	{"jalapeño", "Produce"},
	{"kale", "Produce"},
	{"kiwi", "Produce"},
	{"leek", "Produce"},
	{"lemon", "Produce"},
	{"lettuce", "Produce"},
	{"lime", "Produce"},
	{"mango", "Produce"},
	{"melon", "Produce"},
	{"mint", "Produce"},
	{"mushroom", "Produce"},
	{"onion", "Produce"},
	{"orange", "Produce"},
	{"parsley", "Produce"},
	{"peach", "Produce"},
	{"pear", "Produce"},
	{"pepper", "Produce"},
	{"pineapple", "Produce"},
	{"plum", "Produce"},
	{"potato", "Produce"},
	{"pumpkin", "Produce"},
	{"radish", "Produce"},
	{"raspberry", "Produce"},
	{"rosemary", "Produce"},
	{"scallion", "Produce"},
	{"shallot", "Produce"},
	{"spinach", "Produce"},
	{"squash", "Produce"},
	{"strawberry", "Produce"},
	{"thyme", "Produce"},
	{"tomato", "Produce"},
	{"turnip", "Produce"},
	{"watercress", "Produce"},
	{"watermelon", "Produce"},
	{"yam", "Produce"},
	{"zucchini", "Produce"},

	// Dairy
	{"butter", "Dairy"},
	{"cheddar", "Dairy"},
	{"cheese", "Dairy"},
	{"cottage cheese", "Dairy"},
	{"cream", "Dairy"},
	{"cream cheese", "Dairy"},
	{"egg", "Dairy"},
	{"feta", "Dairy"},
	{"gouda", "Dairy"},
	{"greek yogurt", "Dairy"},
	{"half and half", "Dairy"},
	{"heavy cream", "Dairy"},
	{"milk", "Dairy"},
	{"mozzarella", "Dairy"},
	{"parmesan", "Dairy"},
	{"provolone", "Dairy"},
	{"ricotta", "Dairy"},
	{"sour cream", "Dairy"},
	{"whipped cream", "Dairy"},
	{"yogurt", "Dairy"},

	// Meat
	{"bacon", "Meat"},
	{"beef", "Meat"},
	{"chicken", "Meat"},
	{"chorizo", "Meat"},
	{"ground beef", "Meat"},
	{"ground pork", "Meat"},
	{"ground turkey", "Meat"},
	{"ham", "Meat"},
	{"lamb", "Meat"},
	{"pork", "Meat"},
	{"prosciutto", "Meat"},
	{"salami", "Meat"},
	{"sausage", "Meat"},
	{"steak", "Meat"},
	{"turkey", "Meat"},
	{"veal", "Meat"},
	{"venison", "Meat"},

	// Seafood
	{"clam", "Seafood"},
	{"crab", "Seafood"},
	{"fish", "Seafood"},
	{"lobster", "Seafood"},
	{"oyster", "Seafood"},
	{"salmon", "Seafood"},
	{"scallop", "Seafood"},
	{"shrimp", "Seafood"},
	{"tilapia", "Seafood"},
	{"tuna", "Seafood"},

	// Bakery (single-word)
	{"bagel", "Bakery"},
	{"bread", "Bakery"},
	{"baguette", "Bakery"},
	{"muffin", "Bakery"},
	{"tortilla", "Bakery"},
	{"pita", "Bakery"},
	{"naan", "Bakery"},
	{"flatbread", "Bakery"},

	// Baking (single-word)
	{"flour", "Baking"},
	{"sugar", "Baking"},
	{"yeast", "Baking"},
	{"honey", "Baking"},
	{"oats", "Baking"},
	{"oatmeal", "Baking"},
	{"shortening", "Baking"},
	{"molasses", "Baking"},
	{"gelatin", "Baking"},

	// Spices / Condiments
	{"salt", "Spices"},
	{"pepper", "Spices"},
	{"cumin", "Spices"},
	{"paprika", "Spices"},
	{"turmeric", "Spices"},
	{"cinnamon", "Spices"},
	{"oregano", "Spices"},
	{"chili powder", "Spices"},
	{"cayenne", "Spices"},
	{"nutmeg", "Spices"},
	{"bay leaves", "Spices"},
	{"cloves", "Spices"},
	{"cardamom", "Spices"},
	{"curry", "Spices"},
	{"saffron", "Spices"},
	{"peanut butter", "Condiments"},
	{"almond butter", "Condiments"},
	{"mustard", "Condiments"},
	{"ketchup", "Condiments"},
	{"mayonnaise", "Condiments"},
	{"hot sauce", "Condiments"},
	{"soy sauce", "Condiments"},
	{"worcestershire", "Condiments"},
	{"vinegar", "Condiments"},
	{"olive oil", "Condiments"},
	{"vegetable oil", "Condiments"},
	{"sesame oil", "Condiments"},
	{"salsa", "Condiments"},
	{"ranch", "Condiments"},

	// Snacks
	{"chips", "Snacks"},
	{"crackers", "Snacks"},
	{"popcorn", "Snacks"},
	{"pretzels", "Snacks"},
	{"granola", "Snacks"},
	{"nuts", "Snacks"},
	{"almonds", "Snacks"},
	{"cashews", "Snacks"},
	{"peanuts", "Snacks"},
	{"walnuts", "Snacks"},
	{"pecans", "Snacks"},
	{"trail mix", "Snacks"},
	{"raisins", "Snacks"},
	{"dried cranberries", "Snacks"},
	{"jerky", "Snacks"},

	// Beverages (single-word)
	{"coffee", "Beverages"},
	{"tea", "Beverages"},
	{"soda", "Beverages"},
	{"beer", "Beverages"},
	{"wine", "Beverages"},
	{"juice", "Beverages"},
	{"water", "Beverages"},
	{"kombucha", "Beverages"},

	// Frozen (single-word)
	{"frozen", "Frozen"},
}
