package mcpserver

import (
	"context"
	"fmt"
	"log/slog"
	"sort"
	"strings"
	"time"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"github.com/jimternet/paprika-3-mcp/internal/paprika"
)

// PaprikaClient defines the interface for interacting with the Paprika API.
// This is implemented by *paprika.Client and can be mocked for testing.
type PaprikaClient interface {
	ListRecipes(ctx context.Context) (*paprika.RecipeList, error)
	GetRecipe(ctx context.Context, uid string) (*paprika.Recipe, error)
	SaveRecipe(ctx context.Context, recipe paprika.Recipe) (*paprika.Recipe, error)
	DeleteRecipe(ctx context.Context, recipe paprika.Recipe) (*paprika.Recipe, error)
	ListMealPlan(ctx context.Context) (*paprika.MealPlanResponse, error)
	SaveMealPlan(ctx context.Context, meal paprika.MealPlan) (*paprika.MealPlan, error)
	DeleteMealPlan(ctx context.Context, uid string) error
	ListGroceries(ctx context.Context) (*paprika.GroceryResponse, error)
	ListGroceryLists(ctx context.Context) (*paprika.GroceryListResponse, error)
	SaveGroceryItem(ctx context.Context, item paprika.GroceryItem) (*paprika.GroceryItem, error)
	DeleteGroceryItem(ctx context.Context, uid string) error
}

// defaultRefreshInterval is the default background cache refresh interval.
const defaultRefreshInterval = 5 * time.Minute

type NewServerOptions struct {
	Version           string
	Username          string
	Password          string
	Logger            *slog.Logger
	RateLimitInterval time.Duration
	CachePath         string
	RefreshInterval   time.Duration
}

func NewServer(opts NewServerOptions) (*Server, error) {
	paprika3, err := paprika.NewClient(opts.Username, opts.Password, opts.Version, opts.Logger, opts.RateLimitInterval)
	if err != nil {
		return nil, err
	}

	refreshInterval := opts.RefreshInterval
	if refreshInterval <= 0 {
		refreshInterval = defaultRefreshInterval
	}

	cache := paprika.NewCache(paprika3, opts.CachePath, opts.Logger)

	s := server.NewMCPServer("paprika-3-mcp", opts.Version, server.WithResourceCapabilities(false, false))
	return &Server{
		paprika3:        paprika3,
		cache:           cache,
		server:          s,
		logger:          opts.Logger,
		refreshInterval: refreshInterval,
	}, nil
}

type Server struct {
	paprika3        PaprikaClient
	cache           *paprika.Cache
	logger          *slog.Logger
	server          *server.MCPServer
	refreshInterval time.Duration
}

func (s *Server) Start() {
	ctx := context.Background()

	// Load from disk synchronously (fast — no network). If the cache was empty
	// the Load marks a first-fill so the next Refresh uses concurrent workers.
	if err := s.cache.Load(); err != nil {
		s.logger.Error("failed to load recipe cache from disk", "error", err)
	}

	// First Refresh runs in the background so ServeStdio starts immediately
	// and Claude Desktop does not time out the initialize handshake.
	go func() {
		if err := s.cache.Refresh(ctx); err != nil {
			s.logger.Error("initial cache refresh failed; serving with cached data", "error", err)
		}
		s.registerCachedResources()
	}()

	// Background refresh ticker.
	go func() {
		ticker := time.NewTicker(s.refreshInterval)
		defer ticker.Stop()
		for range ticker.C {
			if err := s.cache.Refresh(ctx); err != nil {
				s.logger.Error("background cache refresh failed", "error", err)
			}
			s.registerCachedResources()
		}
	}()

	createRecipeTool := mcp.NewTool("create_paprika_recipe",
		mcp.WithDescription("Save new recipes generated by LLMs in the Paprika 3 app"),
		mcp.WithString("name", mcp.Description("The name of the recipe"), mcp.Required()),
		mcp.WithString("ingredients", mcp.Description("The ingredients of the recipe"), mcp.Required()),
		mcp.WithString("directions", mcp.Description("The directions for the recipe"), mcp.Required()),
		mcp.WithString("description", mcp.Description("The description of the recipe"), mcp.DefaultString("")),
		mcp.WithString("notes", mcp.Description("The notes for the recipe"), mcp.DefaultString("")),
		mcp.WithString("servings", mcp.Description("The number of servings for the recipe"), mcp.DefaultString("")),
		mcp.WithString("prep_time", mcp.Description("The prep time for the recipe"), mcp.DefaultString("")),
		mcp.WithString("cook_time", mcp.Description("The cook time for the recipe"), mcp.DefaultString("")),
		mcp.WithString("source", mcp.Description("The source of the recipe"), mcp.DefaultString("")),
		mcp.WithString("source_url", mcp.Description("The URL of the source of the recipe"), mcp.DefaultString("")),
		mcp.WithString("difficulty", mcp.Description("The difficulty of the recipe"), mcp.DefaultString("")),
	)
	updateRecipeTool := mcp.NewTool("update_paprika_recipe",
		mcp.WithDescription("Update existing recipes in the Paprika 3 app. Only uid is required; all other fields are optional and will be merged into the existing recipe — fields not provided are preserved as-is. If the recipe is not in the local cache, run refresh_recipes first."),
		mcp.WithString("uid", mcp.Description("The UID of the recipe to update"), mcp.Required()),
		mcp.WithString("name", mcp.Description("The name of the recipe"), mcp.DefaultString("")),
		mcp.WithString("ingredients", mcp.Description("The ingredients of the recipe"), mcp.DefaultString("")),
		mcp.WithString("directions", mcp.Description("The directions for the recipe"), mcp.DefaultString("")),
		mcp.WithString("description", mcp.Description("The description of the recipe"), mcp.DefaultString("")),
		mcp.WithString("notes", mcp.Description("The notes for the recipe"), mcp.DefaultString("")),
		mcp.WithString("servings", mcp.Description("The number of servings for the recipe"), mcp.DefaultString("")),
		mcp.WithString("prep_time", mcp.Description("The prep time for the recipe"), mcp.DefaultString("")),
		mcp.WithString("cook_time", mcp.Description("The cook time for the recipe"), mcp.DefaultString("")),
		mcp.WithString("source", mcp.Description("The source of the recipe"), mcp.DefaultString("")),
		mcp.WithString("source_url", mcp.Description("The URL of the source of the recipe"), mcp.DefaultString("")),
		mcp.WithString("difficulty", mcp.Description("The difficulty of the recipe"), mcp.DefaultString("")),
	)
	listRecipesTool := mcp.NewTool("list_recipes",
		mcp.WithDescription("List all recipes in the Paprika collection, sorted alphabetically. Data is local and instant. Returns recipe name, UID, description, servings, and timing info. Use get_recipe with a UID to retrieve full details including ingredients and directions. To find recipes by ingredient or description text, use search_recipes instead. Call refresh_recipes to fetch the latest data from Paprika."),
		mcp.WithNumber("limit", mcp.Description("Maximum number of recipes to return. 0 means no limit."), mcp.DefaultNumber(0)),
		mcp.WithString("category", mcp.Description("Optional category filter. Case-insensitive exact match against recipe categories. Use list_categories to see available categories."), mcp.DefaultString("")),
	)
	searchRecipesTool := mcp.NewTool("search_recipes",
		mcp.WithDescription("Search recipes by keyword across name, ingredients, and description text. Data is local and instant. Use this when you need to find recipes containing a specific ingredient or term. For browsing or listing all recipes, use list_recipes instead. Call refresh_recipes to fetch the latest data from Paprika."),
		mcp.WithString("query", mcp.Description("Search term to match against recipe name, ingredients, and description. Case-insensitive. Multiple words are AND-matched (e.g. 'chicken pasta' finds recipes containing both words)."), mcp.Required()),
		mcp.WithNumber("limit", mcp.Description("Maximum number of matching recipes to return (default 10)."), mcp.DefaultNumber(10)),
		mcp.WithString("category", mcp.Description("Optional category filter. Case-insensitive exact match against recipe categories. Use list_categories to see available categories."), mcp.DefaultString("")),
	)
	listMealPlanTool := mcp.NewTool("list_meal_plan",
		mcp.WithDescription("List scheduled meals from the Paprika meal plan, grouped by date. Each meal has a UID, name, type (Breakfast/Lunch/Dinner), and optionally a linked recipe UID. Use the meal UID with remove_meal_from_plan to delete entries."),
		mcp.WithString("start_date", mcp.Description("Filter to meals on or after this date. Format: YYYY-MM-DD. If omitted, no lower bound is applied."), mcp.DefaultString("")),
		mcp.WithString("end_date", mcp.Description("Filter to meals on or before this date. Format: YYYY-MM-DD. If omitted, no upper bound is applied."), mcp.DefaultString("")),
	)
	listGroceriesTool := mcp.NewTool("list_groceries",
		mcp.WithDescription("List grocery items across all grocery lists in Paprika. Items are grouped by aisle. Each item includes its list_uid indicating which grocery list it belongs to."),
		mcp.WithString("filter", mcp.Description("Filter by purchase status: 'purchased', 'unpurchased', or 'all'"), mcp.DefaultString("all")),
	)
	addMealTool := mcp.NewTool("add_meal_to_plan",
		mcp.WithDescription("Add a meal to the Paprika meal plan calendar. A meal can optionally be linked to an existing recipe by providing its UID (use search_recipes to find recipe UIDs). Defaults to Dinner if no meal_type is specified."),
		mcp.WithString("date", mcp.Description("Date to schedule the meal. Format: YYYY-MM-DD."), mcp.Required()),
		mcp.WithString("meal_name", mcp.Description("Display name of the meal (e.g. 'Spaghetti Bolognese')"), mcp.Required()),
		mcp.WithNumber("meal_type", mcp.Description("Meal type: 0 = Breakfast, 1 = Lunch, 2 = Dinner. Defaults to 2 (Dinner)."), mcp.DefaultNumber(2)),
		mcp.WithString("recipe_uid", mcp.Description("UID of a Paprika recipe to link to this meal. Optional. Use search_recipes to find recipe UIDs."), mcp.DefaultString("")),
	)
	removeMealTool := mcp.NewTool("remove_meal_from_plan",
		mcp.WithDescription("Remove a meal from the Paprika meal plan. This is a soft delete. Use list_meal_plan to find the meal UID to remove."),
		mcp.WithString("meal_uid", mcp.Description("UID of the meal to remove. Get this from the list_meal_plan results."), mcp.Required()),
	)
	getRecipeTool := mcp.NewTool("get_recipe",
		mcp.WithDescription("Get full recipe details by UID. Data is local and instant. Returns the complete recipe including name, ingredients, directions, prep/cook time, servings, notes, description, categories, source, rating, and creation date as formatted Markdown. Use search_recipes first to find recipe UIDs. Call refresh_recipes to fetch the latest data from Paprika."),
		mcp.WithString("uid", mcp.Description("UID of the recipe. Get this from search_recipes results or from a meal plan entry's recipe_uid."), mcp.Required()),
	)
	listCategoriesTool := mcp.NewTool("list_categories",
		mcp.WithDescription("List all recipe categories with recipe counts. Data is local and instant."),
	)
	refreshRecipesTool := mcp.NewTool("refresh_recipes",
		mcp.WithDescription("Force an immediate refresh from the Paprika API. Use after editing recipes in the Paprika app. Returns cache statistics."),
	)
	listGroceryListsTool := mcp.NewTool("list_grocery_lists",
		mcp.WithDescription("List all grocery/shopping lists in the Paprika account. Paprika supports multiple grocery lists (e.g. one per store). Each list has a UID and a name. One list is marked as the default. Use the list UIDs with add_grocery_item to add items to a specific list."),
	)
	addGroceryItemTool := mcp.NewTool("add_grocery_item",
		mcp.WithDescription("Add an item to a Paprika grocery/shopping list. Aisle is assigned automatically from the user's Paprika history (most accurate), then from a built-in keyword table. Pass aisle or aisle_uid to override. If no list_uid is provided, the item is added to the default list."),
		mcp.WithString("ingredient", mcp.Description("The ingredient/item name"), mcp.Required()),
		mcp.WithString("list_uid", mcp.Description("UID of the grocery list. If omitted, uses the default list. Call list_grocery_lists to discover available lists."), mcp.DefaultString("")),
		mcp.WithString("aisle", mcp.Description("Aisle name override. If omitted, the aisle is looked up automatically. Call list_aisles to see available aisles."), mcp.DefaultString("")),
		mcp.WithString("aisle_uid", mcp.Description("Aisle UID override (takes precedence over aisle name). Call list_aisles to see available aisles and their UIDs."), mcp.DefaultString("")),
		mcp.WithString("quantity", mcp.Description("Quantity needed (optional)"), mcp.DefaultString("")),
		mcp.WithString("recipe", mcp.Description("Recipe this ingredient is for (optional)"), mcp.DefaultString("")),
		mcp.WithString("instruction", mcp.Description("Special instructions (optional)"), mcp.DefaultString("")),
	)
	listAislesTool := mcp.NewTool("list_aisles",
		mcp.WithDescription("List the user's grocery store aisles with name, UID, and sort order. Aisles are defined in Paprika under Settings and synced on every refresh. Use aisle names or UIDs with add_grocery_item to control where items are filed."),
	)
	removeGroceryItemTool := mcp.NewTool("remove_grocery_item",
		mcp.WithDescription("Remove an item from a Paprika grocery list by name. Performs a case-insensitive search across ingredient and item names. If multiple items match, only the first match is removed and the others are reported. This is a soft delete."),
		mcp.WithString("item_name", mcp.Description("Name or partial name of the item to remove. Searches ingredient and item names case-insensitively. Use list_groceries to see current items."), mcp.Required()),
	)
	deleteRecipeTool := mcp.NewTool("delete_recipe",
		mcp.WithDescription("Delete a recipe from Paprika by moving it to the trash (soft delete). The recipe can be recovered from the trash in the Paprika app. Use list_recipes or search_recipes to find the recipe UID."),
		mcp.WithString("uid", mcp.Description("UID of the recipe to delete. Get this from list_recipes or search_recipes results."), mcp.Required()),
	)
	s.server.AddTools(server.ServerTool{
		Tool:    createRecipeTool,
		Handler: s.createRecipe,
	}, server.ServerTool{
		Tool:    updateRecipeTool,
		Handler: s.updateRecipe,
	}, server.ServerTool{
		Tool:    listRecipesTool,
		Handler: s.listRecipes,
	}, server.ServerTool{
		Tool:    searchRecipesTool,
		Handler: s.searchRecipes,
	}, server.ServerTool{
		Tool:    listMealPlanTool,
		Handler: s.listMealPlan,
	}, server.ServerTool{
		Tool:    listGroceriesTool,
		Handler: s.listGroceries,
	}, server.ServerTool{
		Tool:    addMealTool,
		Handler: s.addMealToPlan,
	}, server.ServerTool{
		Tool:    removeMealTool,
		Handler: s.removeMealFromPlan,
	}, server.ServerTool{
		Tool:    getRecipeTool,
		Handler: s.getRecipe,
	}, server.ServerTool{
		Tool:    listGroceryListsTool,
		Handler: s.listGroceryLists,
	}, server.ServerTool{
		Tool:    addGroceryItemTool,
		Handler: s.addGroceryItem,
	}, server.ServerTool{
		Tool:    removeGroceryItemTool,
		Handler: s.removeGroceryItem,
	}, server.ServerTool{
		Tool:    deleteRecipeTool,
		Handler: s.deleteRecipe,
	}, server.ServerTool{
		Tool:    listCategoriesTool,
		Handler: s.listCategories,
	}, server.ServerTool{
		Tool:    refreshRecipesTool,
		Handler: s.refreshRecipes,
	}, server.ServerTool{
		Tool:    listAislesTool,
		Handler: s.listAisles,
	})

	s.logger.Info("serving stdio")
	if err := server.ServeStdio(s.server); err != nil {
		s.logger.Error("server error", "err", err)
	}
}

// registerCachedResources exposes all non-trashed cached recipes as MCP resources.
func (s *Server) registerCachedResources() {
	recipes := s.cache.List()
	for _, recipe := range recipes {
		r := recipe // capture for closure
		resourceContents := mcp.TextResourceContents{
			URI:      fmt.Sprintf("paprika://recipes/%s", r.UID),
			MIMEType: "text/markdown",
			Text:     r.ToMarkdown(),
		}
		s.server.AddResource(
			mcp.NewResource(
				fmt.Sprintf("paprika://recipes/%s", r.UID),
				r.Name,
				mcp.WithResourceDescription(r.ResourceDescription()),
				mcp.WithMIMEType("text/markdown"),
			),
			func(ctx context.Context, request mcp.ReadResourceRequest) ([]mcp.ResourceContents, error) {
				return []mcp.ResourceContents{resourceContents}, nil
			},
		)
	}
	s.logger.Info("registered recipe resources", "count", len(recipes))
}

func (s *Server) createRecipe(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()
	name, err := req.RequireString("name")
	if err != nil || len(name) == 0 {
		return mcp.NewToolResultError("name is required"), nil
	}
	ingredients, err := req.RequireString("ingredients")
	if err != nil || len(ingredients) == 0 {
		return mcp.NewToolResultError("ingredients are required"), nil
	}
	directions, err := req.RequireString("directions")
	if err != nil || len(directions) == 0 {
		return mcp.NewToolResultError("directions are required"), nil
	}
	servings := req.GetString("servings", "")
	prepTime := req.GetString("prep_time", "")
	cookTime := req.GetString("cook_time", "")
	description := req.GetString("description", "")
	notes := req.GetString("notes", "")
	difficulty := req.GetString("difficulty", "")
	source := req.GetString("source", "")
	sourceURL := req.GetString("source_url", "")

	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	recipe, err := s.paprika3.SaveRecipe(ctx, paprika.Recipe{
		Name:        name,
		Ingredients: ingredients,
		Directions:  directions,
		Description: description,
		Servings:    servings,
		PrepTime:    prepTime,
		CookTime:    cookTime,
		Notes:       notes,
		Difficulty:  difficulty,
		Source:      source,
		SourceURL:   sourceURL,
	})
	if err != nil {
		return nil, err
	}

	s.cache.Put(recipe)

	duration := time.Since(start)
	s.logger.Info("Created recipe", "name", recipe.Name, "uid", recipe.UID, "duration", duration)

	return mcp.NewToolResultResource(recipe.Name, mcp.TextResourceContents{
		URI:      fmt.Sprintf("paprika://recipes/%s", recipe.UID),
		MIMEType: "text/markdown",
		Text:     recipe.ToMarkdown(),
	}), nil
}

func (s *Server) updateRecipe(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()
	uid, err := req.RequireString("uid")
	if err != nil || len(uid) == 0 {
		return mcp.NewToolResultError("uid is required"), nil
	}

	// Load the existing recipe from cache; fall back to the live API.
	existing, found := s.cache.Get(uid)
	if !found {
		fetchCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
		defer cancel()
		existing, err = s.paprika3.GetRecipe(fetchCtx, uid)
		if err != nil {
			return mcp.NewToolResultError("recipe not found — try running refresh_recipes first"), nil
		}
	}

	// Copy the cached recipe; only overwrite fields that were explicitly provided
	// (non-empty string supplied by the caller).
	merged := *existing

	if val := req.GetString("name", ""); val != "" {
		merged.Name = val
	}
	if val := req.GetString("ingredients", ""); val != "" {
		merged.Ingredients = val
	}
	if val := req.GetString("directions", ""); val != "" {
		merged.Directions = val
	}
	if val := req.GetString("description", ""); val != "" {
		merged.Description = val
	}
	if val := req.GetString("notes", ""); val != "" {
		merged.Notes = val
	}
	if val := req.GetString("servings", ""); val != "" {
		merged.Servings = val
	}
	if val := req.GetString("prep_time", ""); val != "" {
		merged.PrepTime = val
	}
	if val := req.GetString("cook_time", ""); val != "" {
		merged.CookTime = val
	}
	if val := req.GetString("difficulty", ""); val != "" {
		merged.Difficulty = val
	}
	if val := req.GetString("source", ""); val != "" {
		merged.Source = val
	}
	if val := req.GetString("source_url", ""); val != "" {
		merged.SourceURL = val
	}

	saveCtx, saveCancel := context.WithTimeout(ctx, 10*time.Second)
	defer saveCancel()
	recipe, err := s.paprika3.SaveRecipe(saveCtx, merged)
	if err != nil {
		return nil, err
	}

	s.cache.Put(recipe)

	duration := time.Since(start)
	s.logger.Info("Updated recipe", "name", recipe.Name, "uid", recipe.UID, "duration", duration)

	return mcp.NewToolResultResource(recipe.Name, mcp.TextResourceContents{
		URI:      fmt.Sprintf("paprika://recipes/%s", recipe.UID),
		MIMEType: "text/markdown",
		Text:     recipe.ToMarkdown(),
	}), nil
}


func formatRecipeList(recipes []paprika.Recipe) string {
	var resultText strings.Builder
	for i, recipe := range recipes {
		resultText.WriteString(fmt.Sprintf("%d. **%s**\n", i+1, recipe.Name))
		if recipe.Description != "" {
			resultText.WriteString(fmt.Sprintf("   _%s_\n", recipe.Description))
		}
		resultText.WriteString(fmt.Sprintf("   UID: %s\n", recipe.UID))
		if recipe.Servings != "" {
			resultText.WriteString(fmt.Sprintf("   Servings: %s\n", recipe.Servings))
		}
		if recipe.PrepTime != "" || recipe.CookTime != "" {
			timeInfo := ""
			if recipe.PrepTime != "" {
				timeInfo += fmt.Sprintf("Prep: %s", recipe.PrepTime)
			}
			if recipe.CookTime != "" {
				if timeInfo != "" {
					timeInfo += ", "
				}
				timeInfo += fmt.Sprintf("Cook: %s", recipe.CookTime)
			}
			resultText.WriteString(fmt.Sprintf("   Time: %s\n", timeInfo))
		}
		resultText.WriteString("\n")
	}
	return resultText.String()
}

func (s *Server) listRecipes(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()

	filling := s.cache.IsFilling()
	if filling {
		s.logger.Warn("list_recipes called during initial fill; returning partial cache")
	}

	limit := req.GetInt("limit", 0)
	category := strings.TrimSpace(req.GetString("category", ""))

	// Use cache; List() already returns sorted, non-trashed recipes.
	recipePointers := s.cache.List()
	recipes := make([]paprika.Recipe, 0, len(recipePointers))
	for _, r := range recipePointers {
		if category != "" && !recipeHasCategory(r, category) {
			continue
		}
		recipes = append(recipes, *r)
	}

	if limit > 0 && len(recipes) > limit {
		recipes = recipes[:limit]
	}

	duration := time.Since(start)
	s.logger.Info("Listed recipes", "count", len(recipes), "duration", duration)

	var resultText strings.Builder
	if category != "" {
		resultText.WriteString(fmt.Sprintf("# Recipes in \"%s\"\n\n", category))
	} else {
		resultText.WriteString("# All Recipes\n\n")
	}
	if len(recipes) == 0 {
		resultText.WriteString("No recipes found in your collection.\n")
	} else {
		resultText.WriteString(fmt.Sprintf("Found %d recipe(s):\n\n", len(recipes)))
		resultText.WriteString(formatRecipeList(recipes))
	}

	if filling {
		resultText.WriteString("\n_(Note: initial sync is still in progress — this list may be incomplete. It will complete automatically in the background.)_\n")
	}
	return mcp.NewToolResultText(resultText.String()), nil
}

func (s *Server) searchRecipes(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()

	filling := s.cache.IsFilling()
	if filling {
		s.logger.Warn("search_recipes called during initial fill; returning partial cache")
	}

	query := strings.TrimSpace(req.GetString("query", ""))
	if query == "" {
		return mcp.NewToolResultError("query is required — use list_recipes to browse all recipes"), nil
	}

	limit := req.GetInt("limit", 10)
	category := strings.TrimSpace(req.GetString("category", ""))

	// Use cache Search which handles lowercasing, word splitting, and sorting.
	// Search with unlimited results when category filtering is needed, then apply the category filter.
	searchLimit := limit
	if category != "" {
		searchLimit = 0 // fetch all matches, then filter by category
	}
	matchedPointers := s.cache.Search(query, searchLimit)

	matched := make([]paprika.Recipe, 0, len(matchedPointers))
	for _, r := range matchedPointers {
		if category != "" && !recipeHasCategory(r, category) {
			continue
		}
		matched = append(matched, *r)
	}
	if category != "" && limit > 0 && len(matched) > limit {
		matched = matched[:limit]
	}

	duration := time.Since(start)
	s.logger.Info("Search completed", "query", query, "matches", len(matched), "duration", duration)

	var resultText strings.Builder
	resultText.WriteString(fmt.Sprintf("# Search Results for \"%s\"\n\n", query))
	if category != "" {
		resultText.WriteString(fmt.Sprintf("Filtered by category: \"%s\"\n\n", category))
	}
	if len(matched) == 0 {
		resultText.WriteString("No recipes found matching your search.\n")
	} else {
		resultText.WriteString(fmt.Sprintf("Found %d recipe(s):\n\n", len(matched)))
		resultText.WriteString(formatRecipeList(matched))
	}
	if filling {
		resultText.WriteString("\n_(Note: initial sync is still in progress — results may be incomplete. It will complete automatically in the background.)_\n")
	}

	return mcp.NewToolResultText(resultText.String()), nil
}

func (s *Server) addGroceryItem(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()

	ingredient, err := req.RequireString("ingredient")
	if err != nil || ingredient == "" {
		return mcp.NewToolResultError("ingredient is required"), nil
	}

	listUID := strings.TrimSpace(req.GetString("list_uid", ""))
	aisleOverrideName := strings.TrimSpace(req.GetString("aisle", ""))
	aisleOverrideUID := strings.TrimSpace(req.GetString("aisle_uid", ""))
	quantity := strings.TrimSpace(req.GetString("quantity", ""))
	recipe := strings.TrimSpace(req.GetString("recipe", ""))
	instruction := strings.TrimSpace(req.GetString("instruction", ""))

	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	// Paprika orphans grocery items posted with an empty list_uid: the POST
	// returns 200 but the item is attached to no list and never surfaces in the
	// app (meals are unaffected because they key off date, not a list). When the
	// caller doesn't specify a list, resolve the account's default grocery list
	// and attach the item to it — the behavior this tool already advertises.
	if listUID == "" {
		lists, err := s.paprika3.ListGroceryLists(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to resolve default grocery list: %w", err)
		}
		for _, l := range lists.Result {
			if l.IsDefault {
				listUID = l.UID
				break
			}
		}
		if listUID == "" {
			return mcp.NewToolResultError("no default grocery list found; pass an explicit list_uid"), nil
		}
	}

	// Resolve aisle: uid override > name override > automatic lookup > none.
	var aisleName, aisleUID, aisleReason string
	switch {
	case aisleOverrideUID != "":
		if a, ok := s.cache.AisleByUID(aisleOverrideUID); ok {
			aisleName = a.Name
			aisleUID = a.UID
			aisleReason = "specified"
		}
	case aisleOverrideName != "":
		if a, ok := s.cache.AisleByName(aisleOverrideName); ok {
			aisleName = a.Name
			aisleUID = a.UID
			aisleReason = "specified"
		} else {
			// Caller provided a name that doesn't match any known aisle; use it
			// as-is so the item lands somewhere rather than in Miscellaneous.
			aisleName = aisleOverrideName
			aisleReason = "specified"
		}
	default:
		if name, reason := s.cache.LookupIngredientAisle(ingredient); name != "" {
			if a, ok := s.cache.AisleByName(name); ok {
				aisleName = a.Name
				aisleUID = a.UID
				aisleReason = reason
			}
		}
	}

	item := paprika.GroceryItem{
		Ingredient:  ingredient,
		Name:        ingredient,
		ListUID:     listUID,
		Aisle:       aisleName,
		AisleUID:    aisleUID,
		Quantity:    quantity,
		Recipe:      recipe,
		Instruction: instruction,
	}

	savedItem, err := s.paprika3.SaveGroceryItem(ctx, item)
	if err != nil {
		return nil, fmt.Errorf("failed to add grocery item: %w", err)
	}

	duration := time.Since(start)
	s.logger.Info("added grocery item", "ingredient", ingredient, "aisle", aisleName, "reason", aisleReason, "duration", duration)

	var resultText strings.Builder
	resultText.WriteString("# Grocery Item Added Successfully\n\n")
	resultText.WriteString(fmt.Sprintf("Added **%s** to your grocery list\n\n", ingredient))
	resultText.WriteString(fmt.Sprintf("- **Item**: %s\n", ingredient))
	if quantity != "" {
		resultText.WriteString(fmt.Sprintf("- **Quantity**: %s\n", quantity))
	}
	switch {
	case aisleName != "" && aisleReason == "learned":
		resultText.WriteString(fmt.Sprintf("- **Aisle**: %s _(learned from your history)_\n", aisleName))
	case aisleName != "" && aisleReason == "default":
		resultText.WriteString(fmt.Sprintf("- **Aisle**: %s _(default table)_\n", aisleName))
	case aisleName != "" && aisleReason == "specified":
		resultText.WriteString(fmt.Sprintf("- **Aisle**: %s _(specified)_\n", aisleName))
	default:
		resultText.WriteString("- **Aisle**: Miscellaneous _(no match)_\n")
	}
	if recipe != "" {
		resultText.WriteString(fmt.Sprintf("- **For Recipe**: %s\n", recipe))
	}
	if instruction != "" {
		resultText.WriteString(fmt.Sprintf("- **Instructions**: %s\n", instruction))
	}
	resultText.WriteString(fmt.Sprintf("- **Item ID**: %s\n\n", savedItem.UID))
	resultText.WriteString("The item has been added to your Paprika grocery list.\n")

	return mcp.NewToolResultText(resultText.String()), nil
}

func (s *Server) removeGroceryItem(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()

	// Get item name parameter
	itemName, err := req.RequireString("item_name")
	if err != nil || itemName == "" {
		return mcp.NewToolResultError("item_name is required"), nil
	}

	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	// Get current grocery list to find the item
	groceryResp, err := s.paprika3.ListGroceries(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get grocery list: %w", err)
	}

	// Find matching items (case-insensitive search)
	searchTerm := strings.ToLower(strings.TrimSpace(itemName))
	var matchedItems []paprika.GroceryItem
	for _, item := range groceryResp.Result {
		if strings.Contains(strings.ToLower(item.Ingredient), searchTerm) ||
			strings.Contains(strings.ToLower(item.Name), searchTerm) {
			matchedItems = append(matchedItems, item)
		}
	}

	if len(matchedItems) == 0 {
		return mcp.NewToolResultText(fmt.Sprintf("# No Items Found\n\nNo grocery items found matching \"%s\". Use list_groceries to see your current list.", itemName)), nil
	}

	// If multiple matches, remove the first one but inform the user
	itemToRemove := matchedItems[0]
	err = s.paprika3.DeleteGroceryItem(ctx, itemToRemove.UID)
	if err != nil {
		return nil, fmt.Errorf("failed to remove grocery item: %w", err)
	}

	duration := time.Since(start)
	s.logger.Info("Removed grocery item", "ingredient", itemToRemove.Ingredient, "uid", itemToRemove.UID, "duration", duration)

	// Format result
	var resultText strings.Builder
	resultText.WriteString("# Grocery Item Removed Successfully\n\n")
	resultText.WriteString(fmt.Sprintf("Removed **%s** from your grocery list.\n\n", itemToRemove.Ingredient))

	if len(matchedItems) > 1 {
		resultText.WriteString(fmt.Sprintf("Note: Found %d items matching \"%s\". Removed the first match:\n", len(matchedItems), itemName))
		for i, item := range matchedItems {
			status := "❌ REMOVED"
			if i > 0 {
				status = "⚠️  Still in list"
			}
			resultText.WriteString(fmt.Sprintf("- %s %s", status, item.Ingredient))
			if item.Quantity != "" {
				resultText.WriteString(fmt.Sprintf(" (%s)", item.Quantity))
			}
			resultText.WriteString("\n")
		}
		resultText.WriteString("\nTo remove additional items, run the command again.\n")
	} else {
		resultText.WriteString("The item has been removed from your Paprika grocery list.\n")
	}

	return mcp.NewToolResultText(resultText.String()), nil
}

func (s *Server) getRecipe(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()

	filling := s.cache.IsFilling()
	if filling {
		s.logger.Warn("get_recipe called during initial fill; cache may not have this recipe yet")
	}

	uid, err := req.RequireString("uid")
	if err != nil || uid == "" {
		return mcp.NewToolResultError("uid is required"), nil
	}

	// Try cache first; fall back to live API on miss.
	recipe, found := s.cache.Get(uid)
	if !found {
		fetchCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
		defer cancel()
		var err error
		recipe, err = s.paprika3.GetRecipe(fetchCtx, uid)
		if err != nil {
			if filling {
				return mcp.NewToolResultText("Recipe not yet in cache — initial sync is still in progress. Try again in a moment or call refresh_recipes."), nil
			}
			return nil, fmt.Errorf("failed to get recipe: %w", err)
		}
		s.cache.Put(recipe)
	}

	duration := time.Since(start)
	s.logger.Info("Retrieved recipe", "name", recipe.Name, "uid", recipe.UID, "duration", duration)

	text := recipe.ToMarkdown() + recipeMetadataBlock(recipe)
	return mcp.NewToolResultText(text), nil
}

// recipeHasCategory reports whether r belongs to the given category (case-insensitive).
func recipeHasCategory(r *paprika.Recipe, category string) bool {
	target := strings.ToLower(category)
	for _, c := range r.Categories {
		if strings.ToLower(c) == target {
			return true
		}
	}
	return false
}

// recipeMetadataBlock returns a markdown metadata section for the recipe.
func recipeMetadataBlock(r *paprika.Recipe) string {
	var sb strings.Builder
	sb.WriteString("---\n")
	sb.WriteString(fmt.Sprintf("UID: %s\n", r.UID))
	if len(r.Categories) > 0 {
		sb.WriteString(fmt.Sprintf("Categories: %s\n", strings.Join(r.Categories, ", ")))
	}
	if r.Source != "" {
		sb.WriteString(fmt.Sprintf("Source: %s\n", r.Source))
	}
	if r.SourceURL != "" {
		sb.WriteString(fmt.Sprintf("Source URL: %s\n", r.SourceURL))
	}
	if r.Rating > 0 {
		sb.WriteString(fmt.Sprintf("Rating: %d\n", r.Rating))
	}
	if r.Created != "" {
		sb.WriteString(fmt.Sprintf("Created: %s\n", r.Created))
	}
	sb.WriteString("---\n")
	return sb.String()
}

func (s *Server) listCategories(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()

	filling := s.cache.IsFilling()
	if filling {
		s.logger.Warn("list_categories called during initial fill; returning partial cache")
	}

	recipes := s.cache.List()

	// Collect category counts using case-insensitive dedup (preserve original casing from first seen).
	type catEntry struct {
		display string
		count   int
	}
	byKey := make(map[string]*catEntry)
	for _, r := range recipes {
		for _, cat := range r.Categories {
			key := strings.ToLower(cat)
			if e, ok := byKey[key]; ok {
				e.count++
			} else {
				byKey[key] = &catEntry{display: cat, count: 1}
			}
		}
	}

	// Sort by display name.
	keys := make([]string, 0, len(byKey))
	for k := range byKey {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	duration := time.Since(start)
	s.logger.Info("Listed categories", "count", len(keys), "duration", duration)

	var resultText strings.Builder
	resultText.WriteString("# Recipe Categories\n\n")
	if len(keys) == 0 {
		resultText.WriteString("No categories found. Recipes may not be assigned to categories yet.\n")
	} else {
		resultText.WriteString(fmt.Sprintf("Found %d category/categories:\n\n", len(keys)))
		for _, k := range keys {
			e := byKey[k]
			resultText.WriteString(fmt.Sprintf("- %s (%d recipe", e.display, e.count))
			if e.count != 1 {
				resultText.WriteString("s")
			}
			resultText.WriteString(")\n")
		}
	}
	if filling {
		resultText.WriteString("\n_(Note: initial sync is still in progress — category list may be incomplete.)_\n")
	}

	return mcp.NewToolResultText(resultText.String()), nil
}

func (s *Server) listAisles(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	aisles := s.cache.Aisles()
	var sb strings.Builder
	sb.WriteString("# Grocery Aisles\n\n")
	if len(aisles) == 0 {
		sb.WriteString("No aisles found. Aisles are configured in Paprika under Settings → Grocery Aisles and synced on every refresh. Try calling refresh_recipes.\n")
	} else {
		sb.WriteString(fmt.Sprintf("Found %d aisle(s):\n\n", len(aisles)))
		for _, a := range aisles {
			sb.WriteString(fmt.Sprintf("- **%s** — UID: `%s`\n", a.Name, a.UID))
		}
	}
	return mcp.NewToolResultText(sb.String()), nil
}

func (s *Server) refreshRecipes(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()

	// Use background context: the MCP request context may be short-lived but
	// a refresh on a large collection takes longer than typical RPC timeouts.
	if err := s.cache.Refresh(context.Background()); err != nil {
		return nil, fmt.Errorf("refresh failed: %w", err)
	}
	s.registerCachedResources()

	count, lastSync := s.cache.Stats()
	duration := time.Since(start)
	s.logger.Info("Manual cache refresh complete", "total", count, "duration", duration)

	return mcp.NewToolResultText(fmt.Sprintf(
		"Refreshed. Total: %d recipes. Last sync: %s",
		count,
		lastSync.Format(time.RFC3339),
	)), nil
}

func (s *Server) deleteRecipe(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()

	uid, err := req.RequireString("uid")
	if err != nil || uid == "" {
		return mcp.NewToolResultError("uid is required"), nil
	}

	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	// Fetch the recipe first so we can pass it to DeleteRecipe
	recipe, err := s.paprika3.GetRecipe(ctx, uid)
	if err != nil {
		return nil, fmt.Errorf("failed to get recipe: %w", err)
	}

	_, err = s.paprika3.DeleteRecipe(ctx, *recipe)
	if err != nil {
		return nil, fmt.Errorf("failed to delete recipe: %w", err)
	}

	s.cache.Remove(recipe.UID)

	duration := time.Since(start)
	s.logger.Info("Deleted recipe", "name", recipe.Name, "uid", recipe.UID, "duration", duration)

	var resultText strings.Builder
	resultText.WriteString("# Recipe Deleted Successfully\n\n")
	resultText.WriteString(fmt.Sprintf("Moved **%s** to the trash.\n\n", recipe.Name))
	resultText.WriteString("The recipe can be recovered from the trash in the Paprika app.\n")

	return mcp.NewToolResultText(resultText.String()), nil
}

func (s *Server) addMealToPlan(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()

	// Get parameters
	date, err := req.RequireString("date")
	if err != nil || date == "" {
		return mcp.NewToolResultError("date is required"), nil
	}
	mealName, err := req.RequireString("meal_name")
	if err != nil || mealName == "" {
		return mcp.NewToolResultError("meal_name is required"), nil
	}

	mealType := req.GetInt("meal_type", paprika.MealTypeDinner)
	recipeUID := strings.TrimSpace(req.GetString("recipe_uid", ""))

	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	// Create meal plan entry with ALL required fields
	// Format date correctly: "YYYY-MM-DD 00:00:00"
	formattedDate := date + " 00:00:00"

	meal := paprika.MealPlan{
		Date:      formattedDate,
		Name:      mealName,
		Type:      mealType,
		RecipeUID: recipeUID,
		OrderFlag: 0,
	}

	// Save the meal plan entry
	savedMeal, err := s.paprika3.SaveMealPlan(ctx, meal)
	if err != nil {
		return nil, fmt.Errorf("failed to add meal to plan: %w", err)
	}

	duration := time.Since(start)
	s.logger.Info("Added meal to plan", "date", date, "meal", mealName, "type", mealType, "duration", duration)

	// Format result
	var resultText strings.Builder
	resultText.WriteString("# Meal Added Successfully\n\n")

	mealTypeStr := paprika.MealTypeName(mealType)

	resultText.WriteString(fmt.Sprintf("Added **%s** as %s on %s\n\n", mealName, mealTypeStr, date))
	resultText.WriteString(fmt.Sprintf("- **Date**: %s\n", date))
	resultText.WriteString(fmt.Sprintf("- **Meal**: %s\n", mealName))
	resultText.WriteString(fmt.Sprintf("- **Type**: %s\n", mealTypeStr))
	if recipeUID != "" {
		resultText.WriteString(fmt.Sprintf("- **Recipe ID**: %s\n", recipeUID))
	}
	resultText.WriteString(fmt.Sprintf("- **Meal ID**: %s\n\n", savedMeal.UID))

	resultText.WriteString("The meal has been added to your Paprika meal plan calendar.\n")

	return mcp.NewToolResultText(resultText.String()), nil
}

func (s *Server) removeMealFromPlan(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()

	// Get meal UID parameter
	mealUID, err := req.RequireString("meal_uid")
	if err != nil || mealUID == "" {
		return mcp.NewToolResultError("meal_uid is required"), nil
	}

	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	// Delete the meal plan entry
	if err = s.paprika3.DeleteMealPlan(ctx, mealUID); err != nil {
		return nil, fmt.Errorf("failed to remove meal from plan: %w", err)
	}

	duration := time.Since(start)
	s.logger.Info("Removed meal from plan", "meal_uid", mealUID, "duration", duration)

	// Format result
	var resultText strings.Builder
	resultText.WriteString("# Meal Removed Successfully\n\n")
	resultText.WriteString(fmt.Sprintf("Removed meal with ID **%s** from your meal plan.\n\n", mealUID))
	resultText.WriteString("The meal has been deleted from your Paprika meal plan calendar.\n")

	return mcp.NewToolResultText(resultText.String()), nil
}

func (s *Server) listMealPlan(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()

	// Get date filters if provided
	startDate := strings.TrimSpace(req.GetString("start_date", ""))
	endDate := strings.TrimSpace(req.GetString("end_date", ""))

	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	// Get meal plan from Paprika
	mealPlanResp, err := s.paprika3.ListMealPlan(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get meal plan: %w", err)
	}

	// Filter by date range if specified, and exclude deleted meals
	var filteredMeals []paprika.MealPlan
	for _, meal := range mealPlanResp.Result {
		if meal.Deleted {
			continue
		}
		// Normalize meal date to YYYY-MM-DD for comparison (API returns "YYYY-MM-DD HH:MM:SS")
		mealDate := meal.Date
		if len(mealDate) > 10 {
			mealDate = mealDate[:10]
		}
		if startDate != "" && mealDate < startDate {
			continue
		}
		if endDate != "" && mealDate > endDate {
			continue
		}
		filteredMeals = append(filteredMeals, meal)
	}

	duration := time.Since(start)
	s.logger.Info("Retrieved meal plan", "total", len(mealPlanResp.Result), "filtered", len(filteredMeals), "duration", duration)

	// Format results
	var resultText strings.Builder
	resultText.WriteString("# Meal Plan\n\n")

	if startDate != "" || endDate != "" {
		resultText.WriteString(fmt.Sprintf("Showing meals from %s to %s\n\n", startDate, endDate))
	}

	if len(filteredMeals) == 0 {
		resultText.WriteString("No meals found in the specified date range.\n")
	} else {
		resultText.WriteString(fmt.Sprintf("Found %d scheduled meal(s):\n\n", len(filteredMeals)))

		// Group by date
		mealsByDate := make(map[string][]paprika.MealPlan)
		for _, meal := range filteredMeals {
			mealsByDate[meal.Date] = append(mealsByDate[meal.Date], meal)
		}

		// Sort dates
		dates := make([]string, 0, len(mealsByDate))
		for date := range mealsByDate {
			dates = append(dates, date)
		}
		sort.Strings(dates)

		for _, date := range dates {
			meals := mealsByDate[date]
			resultText.WriteString(fmt.Sprintf("## %s\n", date))

			for _, meal := range meals {
				mealType := paprika.MealTypeName(meal.Type)

				resultText.WriteString(fmt.Sprintf("- **%s**: %s", mealType, meal.Name))
				if meal.RecipeUID != "" {
					resultText.WriteString(fmt.Sprintf(" (Recipe ID: %s)", meal.RecipeUID))
				}
				resultText.WriteString("\n")
			}
			resultText.WriteString("\n")
		}
	}

	return mcp.NewToolResultText(resultText.String()), nil
}

func (s *Server) listGroceryLists(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()

	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	resp, err := s.paprika3.ListGroceryLists(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get grocery lists: %w", err)
	}

	duration := time.Since(start)
	s.logger.Info("Retrieved grocery lists", "count", len(resp.Result), "duration", duration)

	var resultText strings.Builder
	resultText.WriteString("# Grocery Lists\n\n")

	if len(resp.Result) == 0 {
		resultText.WriteString("No grocery lists found.\n")
	} else {
		resultText.WriteString(fmt.Sprintf("Found %d grocery list(s):\n\n", len(resp.Result)))
		for _, list := range resp.Result {
			if list.Deleted {
				continue
			}
			defaultMarker := ""
			if list.IsDefault {
				defaultMarker = " (default)"
			}
			resultText.WriteString(fmt.Sprintf("- **%s**%s\n  UID: %s\n", list.Name, defaultMarker, list.UID))
		}
	}

	return mcp.NewToolResultText(resultText.String()), nil
}

func (s *Server) listGroceries(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()

	// Get filter parameter
	filter := strings.ToLower(strings.TrimSpace(req.GetString("filter", "all")))

	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	// Get groceries from Paprika
	groceryResp, err := s.paprika3.ListGroceries(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get groceries: %w", err)
	}

	// Filter items based on purchase status, excluding deleted items
	var filteredItems []paprika.GroceryItem
	for _, item := range groceryResp.Result {
		if item.Deleted {
			continue
		}
		switch filter {
		case "purchased":
			if item.Purchased {
				filteredItems = append(filteredItems, item)
			}
		case "unpurchased":
			if !item.Purchased {
				filteredItems = append(filteredItems, item)
			}
		default: // "all"
			filteredItems = append(filteredItems, item)
		}
	}

	duration := time.Since(start)
	s.logger.Info("Retrieved groceries", "total", len(groceryResp.Result), "filtered", len(filteredItems), "filter", filter, "duration", duration)

	// Format results
	var resultText strings.Builder
	resultText.WriteString("# Grocery List\n\n")

	if len(filteredItems) == 0 {
		resultText.WriteString("No grocery items found.\n")
	} else {
		resultText.WriteString(fmt.Sprintf("Found %d grocery item(s):\n\n", len(filteredItems)))

		// Group by aisle
		itemsByAisle := make(map[string][]paprika.GroceryItem)
		for _, item := range filteredItems {
			aisle := item.Aisle
			if aisle == "" {
				aisle = "Other"
			}
			itemsByAisle[aisle] = append(itemsByAisle[aisle], item)
		}

		// Sort aisles alphabetically
		aisles := make([]string, 0, len(itemsByAisle))
		for aisle := range itemsByAisle {
			aisles = append(aisles, aisle)
		}
		sort.Strings(aisles)

		for _, aisle := range aisles {
			items := itemsByAisle[aisle]
			resultText.WriteString(fmt.Sprintf("## %s\n", aisle))

			for _, item := range items {
				status := "☐"
				if item.Purchased {
					status = "☑"
				}

				resultText.WriteString(fmt.Sprintf("%s **%s**", status, item.Ingredient))
				if item.Quantity != "" {
					resultText.WriteString(fmt.Sprintf(" (%s)", item.Quantity))
				}
				if item.Recipe != "" {
					resultText.WriteString(fmt.Sprintf(" - for %s", item.Recipe))
				}
				if item.Instruction != "" {
					resultText.WriteString(fmt.Sprintf(" _%s_", item.Instruction))
				}
				resultText.WriteString("\n")
			}
			resultText.WriteString("\n")
		}
	}

	return mcp.NewToolResultText(resultText.String()), nil
}
